Revert "dnsmasq: follow upstream dnsmasq pre-v2.81"
This reverts commit 3c742447973ac853052511147df7228b6284fbbb.

buildbot found an error
option.c: In function 'dhcp_context_free':
option.c:1042:15: error: 'struct dhcp_context' has no member named 'template_interface'
       free(ctx->template_interface);

revert for the moment

Signed-off-by: Kevin Darbyshire-Bryant <ldir@darbyshire-bryant.me.uk>