uboot-layerscape: do not build efimkcapsule tool
OpenWrt layerscape target does not use this command. If the host is
missing gnutls, this tool will fail to build. Fix build error:

tools/mkeficapsule.c:20:10: fatal error: gnutls/gnutls.h: No such file or directory
   20 | #include <gnutls/gnutls.h>
      |          ^~~~~~~~~~~~~~~~~

Fixes: 1c9eb1ad7567 ("uboot-layerscape: bump to lf-6.12.20-2.0.0")
Signed-off-by: Shiji Yang <yangshiji66@outlook.com>
Link: https://github.com/openwrt/openwrt/pull/19836
Signed-off-by: Robert Marko <robimarko@gmail.com>