ath79: 5.15: fix not exported sym ath79_pll_base
ath79_pll_base was declared as extern but no code exported it.
Anyone including arch/mips/include/asm/mach-ath79/ath79.h and compiled
as a module would break with:

ERROR: modpost: "ath79_pll_base" [drivers/net/ethernet/atheros/ag71xx/ag71xx.ko] undefined!

Signed-off-by: Luiz Angelo Daros de Luca <luizluca@gmail.com>